profile_service:
  websocket_api_key: dev_ws_api_key
  rest_api_key: dev_rest_api_key

websocket_server:
  read_deadline: 50
  read_timeout: 50
  write_timeout: 50
  message_size_limit: 1000
  address: "127.0.0.1:8080"
  path: "/ws"
